# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 581abf9178bac42bf3d29da7ceb4c0251068d26d1b10cb305a89b950ae333dd64561cd3c8ece757e9d8d6cfd480052668f3e499e4d0c6b0b48203e4c6543e63a
  WIT_AI_CLIENT_ACCESS_TOKEN: <%= ENV["WIT_AI_CLIENT_ACCESS_TOKEN"] %>
  DARK_SKY_SECRET: <%= ENV["DARK_SKY_SECRET"] %>
  TIMEZONE_DB_KEY: <%= ENV["TIMEZONE_DB_KEY"] %>
  NY_TIMES_ARTICLE_SEARCH_KEY: <%= ENV["NY_TIMES_ARTICLE_SEARCH_KEY"] %>
  NY_TIMES_MOST_POPULAR_KEY: <%= ENV["NY_TIMES_MOST_POPULAR_KEY"] %>
  NY_TIMES_TOP_STORIES_KEY: <%= ENV["NY_TIMES_TOP_STORIES_KEY"] %>
test:
  secret_key_base: c6ec6b3918fbf6c564f6427ce24f9f34883fe54c58681c7a16e37025fdfdfa36881660af1a1b244f802661e348ba44e7c57e28aa2d17c16a4b7a3cc77b1b6850
  WIT_AI_CLIENT_ACCESS_TOKEN: <%= ENV["WIT_AI_CLIENT_ACCESS_TOKEN"] %>
  DARK_SKY_SECRET: <%= ENV["DARK_SKY_SECRET"] %>
  TIMEZONE_DB_KEY: <%= ENV["TIMEZONE_DB_KEY"] %>
  NY_TIMES_ARTICLE_SEARCH_KEY: <%= ENV["NY_TIMES_ARTICLE_SEARCH_KEY"] %>
  NY_TIMES_MOST_POPULAR_KEY: <%= ENV["NY_TIMES_MOST_POPULAR_KEY"] %>
  NY_TIMES_TOP_STORIES_KEY: <%= ENV["NY_TIMES_TOP_STORIES_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  WIT_AI_CLIENT_ACCESS_TOKEN: <%= ENV["WIT_AI_CLIENT_ACCESS_TOKEN"] %>
  DARK_SKY_SECRET: <%= ENV["DARK_SKY_SECRET"] %>
  TIMEZONE_DB_KEY: <%= ENV["TIMEZONE_DB_KEY"] %>
  NY_TIMES_ARTICLE_SEARCH_KEY: <%= ENV["NY_TIMES_ARTICLE_SEARCH_KEY"] %>
  NY_TIMES_MOST_POPULAR_KEY: <%= ENV["NY_TIMES_MOST_POPULAR_KEY"] %>
  NY_TIMES_TOP_STORIES_KEY: <%= ENV["NY_TIMES_TOP_STORIES_KEY"] %>
